- repo: git://github.com/kintoandar/pre-commit.git
  sha: v2.1.0
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: end-of-file-fixer
